import Hero from "@/components/HomePage/Hero";
import Section2 from "@/components/HomePage/Section2";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <Section2 />
    </>
  );
};

export default Home;
